"""Read-only release readiness for the authorized Golden Demo corpus.

The service intentionally reports missing production material as BLOCKED.  It
never downloads papers, creates Evidence, invokes a model, or changes state.
"""
from __future__ import annotations

from pathlib import Path

from sqlalchemy import func, select

from app.models.ai_mission import AIMission
from app.models.approval import ApprovalRequest
from app.models.artifact import Artifact
from app.models.computer_mission import ComputerMission
from app.models.governance import GovernanceWorkspace, WorkspaceUserRole
from app.models.paper import Paper
from app.models.paper_chunk import PaperChunk
from app.services.database import SessionLocal
from app.services.identity_service import IdentityService
from app.services.vector_store import INDEX_PATH, MAPPING_PATH


class DemoReadinessService:
    """Summarize only persisted, observable preconditions for a live demo."""

    MINIMUM_PAPERS = 5

    def __init__(self, session_factory=SessionLocal, *, index_path: Path = INDEX_PATH, mapping_path: Path = MAPPING_PATH) -> None:
        self._sessions = session_factory
        self._index_path = index_path
        self._mapping_path = mapping_path

    @staticmethod
    def _state(passed: bool) -> str:
        return "PASS" if passed else "BLOCKED"

    def snapshot(self) -> dict[str, object]:
        session = self._sessions()
        try:
            workspace = session.scalar(select(GovernanceWorkspace).where(
                GovernanceWorkspace.name == IdentityService.demo_workspace_name
            ))
            workspace_id = workspace.id if workspace else None
            members = int(session.scalar(select(func.count(WorkspaceUserRole.id)).where(
                WorkspaceUserRole.workspace_id == workspace_id
            )) or 0) if workspace_id else 0
            papers = int(session.scalar(select(func.count(Paper.paper_id))) or 0)
            chunks = int(session.scalar(select(func.count(PaperChunk.id))) or 0)
            embeddings = int(session.scalar(select(func.count(PaperChunk.id)).where(
                PaperChunk.embedding != ""
            )) or 0)
            mission_count = int(session.scalar(select(func.count()).select_from(Artifact).join(
                AIMission, Artifact.mission_id == AIMission.id,
            ).where(AIMission.workspace_id == workspace_id)) or 0) if workspace_id else 0
            reviews = int(session.scalar(select(func.count(ApprovalRequest.id)).where(
                ApprovalRequest.workspace_id == workspace_id
            )) or 0) if workspace_id else 0
            computer = int(session.scalar(select(func.count(ComputerMission.id)).join(
                AIMission, ComputerMission.mission_id == AIMission.id,
            ).where(AIMission.workspace_id == workspace_id)) or 0) if workspace_id else 0
        finally:
            session.close()

        faiss_ready = self._index_path.exists() and self._mapping_path.exists()
        corpus_ready = papers >= self.MINIMUM_PAPERS and chunks > 0 and embeddings > 0 and faiss_ready
        checks = [
            {"id": "demo_workspace", "status": self._state(bool(workspace_id)), "detail": "Demo Workspace is provisioned." if workspace_id else "Demo Workspace is not provisioned."},
            {"id": "demo_members", "status": self._state(members > 0), "detail": f"{members} persisted Demo member(s)." if members else "No Demo membership is available."},
            {"id": "demo_corpus", "status": self._state(corpus_ready), "detail": f"{papers} real paper(s), {chunks} chunk(s), {embeddings} embedded chunk(s); FAISS {'available' if faiss_ready else 'missing'}."},
            {"id": "research", "status": self._state(corpus_ready), "detail": "Research can be grounded in the persisted corpus." if corpus_ready else "Research is blocked until the real corpus is indexed."},
            {"id": "evidence_review", "status": "NOT VERIFIED" if corpus_ready else "BLOCKED", "detail": "Requires a live Mission, candidate Evidence and human review; this check never fabricates them."},
            {"id": "artifact", "status": "NOT VERIFIED" if mission_count else "BLOCKED", "detail": "Requires an approved live Mission output; no Artifact is generated by readiness checks."},
            {"id": "computer", "status": "NOT VERIFIED" if computer else "BLOCKED", "detail": "Requires a controlled Computer Mission; no task is created by readiness checks."},
        ]
        return {
            "overall": "PASS" if all(item["status"] == "PASS" for item in checks[:4]) else "BLOCKED",
            "demo_workspace_id": workspace_id,
            "counts": {"members": members, "papers": papers, "chunks": chunks, "embeddings": embeddings, "artifact_backed_missions": mission_count, "reviews": reviews, "computer_missions": computer},
            "corpus_scope": "The current paper library is deployment-level. Only authorized material may be seeded; no synthetic Evidence, approval, insight or Artifact is created.",
            "checks": checks,
        }
